<<<<<<< HEAD
trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
   azureSubscription: 'Azure subscription'
   keyVaultName: ''

jobs: 
  - job: Deploy
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: ''
        KeyVaultName: ''
        SecretsFilter: '*'
        RunAsPreJob: false

    - pwsh: ./script.ps1

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ''
        subscriptionId: 
        action: 'Create Or Update Resource Group'
        resourceGroupName: ''
        location: 'UK West'
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        csmParametersFile: 'main.bicepparam'
        deploymentMode: 'Incremental'
=======
# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
>>>>>>> 0a5c309665f12349ee0dd5dadc8e2c5bf54aadd9
