trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
   azureSubscription: 'Azure subscription 1'
   keyVaultName: 'NetflixSecret'

jobs: 
  - job: Deploy
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Netflix'
        KeyVaultName: 'NetflixSecret'
        SecretsFilter: '*'
        RunAsPreJob: false

    - pwsh: ./script.ps1

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'Netflix'
        subscriptionId: 488dbdc5-85c6-402d-811f-eb47d17f391f
        action: 'Create Or Update Resource Group'
        resourceGroupName: 'NetflixProject'
        location: 'ukwest'
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        csmParametersFile: 'main.bicepparam'
        deploymentMode: 'Validation'
    # Add more steps here if needed