trigger: none

pool:
  vmImage: ubuntu-latest
  
variables:
   azureSubscription: 'Azure subscription'
   keyVaultName: ''

jobs: 
  - job: Deploy
    steps:
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: ''
        KeyVaultName: ''
        SecretsFilter: '*'
        RunAsPreJob: false

    - pwsh: ./script.ps1

    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: ''
        subscriptionId: 
        action: 'Create Or Update Resource Group'
        resourceGroupName: ''
        location: 'UK West'
        templateLocation: 'Linked artifact'
        csmFile: 'main.bicep'
        csmParametersFile: 'main.bicepparam'
        deploymentMode: 'Incremental'
